services:
  postgresdb:
    build:
      .
      # dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: nestjscourse
    #   POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    # volumes:
    #   - data_sql:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: johndoe@example.org
      PGADMIN_DEFAULT_PASSWORD: nestjscourse
    ports:
      - "80:80"

# volumes:
#   data_sql:

